version: '2.1'

services:
  chroma:
    image: chromadb/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - "8000:8000"
    container_name: chroma
    healthcheck:
      test: stat /etc/passwd
      interval: 20s
      timeout: 60s
      start_period: 15s
volumes:
  index_data:
    driver: local
